plugins {
    id "fabric-loom" version "1.17-SNAPSHOT"
}

base {
    archivesName = "${project.mod_id}-fabric"
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"

    mappings loom.officialMojangMappings()

    // =====================================================
    // Fabric
    // =====================================================

    modImplementation("net.fabricmc:fabric-loader:${fabric_loader_version}")

    modImplementation("net.fabricmc.fabric-api:fabric-api:${fabric_api_version}")

    modImplementation("net.fabricmc:fabric-language-kotlin:${fabric_kotlin_version}")

    // Architectury API
    modImplementation("maven.modrinth:lhGA9TYQ:uNdfrcQ8")

    // UI Lib
    modImplementation("curse.maven:ui-933200:7650065")

    // YAML Config
    modImplementation("curse.maven:yaml-config-1128669:8188613")

    // Arc Lib
    modImplementation("curse.maven:arc-883593:7654922")

    // Item Restrictions
    modImplementation("curse.maven:item-restrictions-887774:7650342")

    // TerraBlender
    modImplementation("maven.modrinth:kkmrDlKT:${terrablender_fabric_id}")

    // Lithostitched
    modImplementation("maven.modrinth:XaDC71GB:pLbQKCOo")

    // Moog's Structure Lib
    modImplementation("maven.modrinth:1oUDhxuy:2idiRwR3")

    // Geckolib
    modImplementation("maven.modrinth:8BmcQJ2H:G1BvHQDL")

//    // YetAnotherConfigLib (YACL)
//    modImplementation("maven.modrinth:1eAoo2KR:pHWDw3Vc")

    // NightConfig
    modImplementation("com.electronwill.night-config:core:3.8.1")
    modImplementation("com.electronwill.night-config:toml:3.8.1")

    // JEI compile only
    modCompileOnlyApi("mezz.jei:jei-${minecraft_version}-fabric-api:latest.release")

    // JEI runtime
    modRuntimeOnly("mezz.jei:jei-${minecraft_version}-fabric:latest.release")

    // Better Combat
    modImplementation("maven.modrinth:5sy6g3kz:MLmCv38Y")

    // Player Animation Library
    modImplementation("com.zigythebird.playeranim:PlayerAnimationLibFabric:1.1.10+mc.1.21.11")

    // Cloth Config API for Better Combat
    modImplementation("maven.modrinth:9s6osm5g:xuX40TN5")

    // Tiny Config for Better Combat
    modImplementation("maven.modrinth:EivZOK5a:Cn6nGALI")

    // =====================================================
    // Common
    // =====================================================

    implementation project(
            path: ":common",
            configuration: "namedElements"
    )
}

loom {
    mods {
        "${project.mod_id}" {
            sourceSet sourceSets.main
            sourceSet("main", ":common")
        }
    }

    runs {
        client {
            client()
            name = "Fabric Client"
        }

        server {
            server()
            name = "Fabric Server"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}

tasks.processResources {
    inputs.properties(
            "version": project.version,
            "minecraft_version": project.minecraft_version,
            "fabric_loader_version": project.fabric_loader_version
    )

    filesMatching("fabric.mod.json") {
        expand(
                "version": project.version,
                "minecraft_version": project.minecraft_version,
                "fabric_loader_version": project.fabric_loader_version
        )
    }
}