plugins {
	id "org.jetbrains.kotlin.jvm" version "2.4.10" apply false
}

allprojects {
	group = project.mod_group
	version = project.mod_version

	repositories {
		mavenCentral()

		// Modrinth
		maven {
			name = "Modrinth"
			url = "https://api.modrinth.com/maven"
		}

		// CurseForge
		maven {
			name = "CurseMaven"
			url = "https://www.cursemaven.com"
		}

		// DAQEM
		maven {
			name = "DAQEM"
			url = "https://maven.daqem.com/releases"
		}

		// Fabric
		maven {
			name = "Fabric"
			url = "https://maven.fabricmc.net/"
		}

		// NeoForge
		maven {
			name = "NeoForge"
			url = "https://maven.neoforged.net/releases/"
		}

		// Architectury
		maven {
			name = "Architectury"
			url = "https://maven.architectury.dev/"
		}
	}
}

subprojects {
	apply plugin: "org.jetbrains.kotlin.jvm"

	java {
		toolchain {
			languageVersion = JavaLanguageVersion.of(21)
		}

		withSourcesJar()
	}

	kotlin {
		jvmToolchain(21)
	}

	tasks.withType(JavaCompile).configureEach {
		options.release = 21
	}
}