buildscript {
	repositories {
		mavenCentral()
		gradlePluginPortal()
		maven {
			name = "Architectury"
			url = "https://maven.architectury.dev/"
		}
	}

	dependencies {
		classpath("gradle.plugin.org.jetbrains.gradle.plugin.idea-ext:gradle-idea-ext:1.4.1")
	}
}

plugins {
	id "architectury-plugin" version "3.5-SNAPSHOT" apply false
	id "dev.architectury.loom" version "1.17-SNAPSHOT" apply false
	id "org.jetbrains.kotlin.jvm" version "2.4.20" apply false
}

allprojects {
	group = project.mod_group
	version = project.mod_version

	repositories {
		mavenCentral()

		// Modrinth
		maven {
			name = "Modrinth"
			url = "https://api.modrinth.com/maven"
		}

		// CurseForge
		maven {
			name = "CurseForge"
			url = "https://www.cursemaven.com"
		}

		// DAQEM
		maven {
			name = "DAQEM"
			url = "https://maven.daqem.com/releases"
		}

		// Fabric
		maven {
			name = "Fabric"
			url = "https://maven.fabricmc.net/"
		}

		// NeoForge
		maven {
			name = "NeoForge"
			url = "https://maven.neoforged.net/releases/"
		}

		// Architectury
		maven {
			name = "Architectury"
			url = "https://maven.architectury.dev/"
		}

		// JEI
		maven {
			name = "Jared's maven"
			url = "https://maven.blamejared.com/"
		}

		maven {
			name = "RedlanceMinecraft"
			url = uri("https://repo.redlance.org/public")
		}
	}
}

subprojects {
	apply plugin: "java"
	apply plugin: "org.jetbrains.kotlin.jvm"
	apply plugin: "architectury-plugin"

	java {
		toolchain {
			languageVersion = JavaLanguageVersion.of(21)
		}

		withSourcesJar()
	}

	kotlin {
		jvmToolchain(21)
	}

	tasks.withType(JavaCompile).configureEach {
		options.release = 21
	}
}