org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Minecraft
minecraft_version=1.21.11

# Mod
mod_id=aris
mod_name=Aris
mod_version=1.0.0
mod_group=com.grindlesstudio.aris
mod_author=Tenakt

# Fabric
fabric_loader_version=0.19.3
fabric_api_version=0.141.6+1.21.11
fabric_kotlin_version=1.13.13+kotlin.2.4.10
yarn_mappings=1.21.11+build.3

# TerraBlender
terrablender_version=21.11.0.0
terrablender_fabric_id=chxo508B
terrablender_neoforge_id=xjrV1Uvq

# NeoForge
neoforge_version=21.11.17-beta

# Knot
knot_version=19.1.0

# Java
java_version=21