pluginManagement {
	repositories {
		maven {
			name = "Fabric"
			url = "https://maven.fabricmc.net/"
		}

		maven {
			name = "NeoForge"
			url = "https://maven.neoforged.net/releases/"
		}

		gradlePluginPortal()
		mavenCentral()
	}
}

rootProject.name = "aris"

include("common")
include("fabric")
include("neoforge")