plugins {
    id "dev.architectury.loom"
}

architectury {
    common("fabric", "neoforge")
}

base {
    archivesName = "${project.mod_id}-common"
}

repositories {
    maven {
        name = "Fabric"
        url = "https://maven.fabricmc.net/"
    }

    maven {
        name = "CurseMaven"
        url = "https://www.cursemaven.com"
    }

    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
    }

    maven {
        name = "Architectury"
        url = "https://maven.architectury.dev/"
    }

    maven {
        name = "DAQEM"
        url = "https://maven.daqem.com/releases"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"

    mappings loom.officialMojangMappings()

    // DAQEM
    modImplementation("com.daqem.knot:knot-common:${knot_version}")
    modImplementation "com.daqem.arc:arc-common:${arc_version}"
    modImplementation "com.daqem.uilib:uilib-common:${uilib_version}"
    modImplementation "com.daqem.yamlconfig:yamlconfig-common:${yamlconfig_version}"

    modImplementation "dev.architectury:architectury:${architectury_version}"
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}