plugins {
    id "dev.architectury.loom"
}

architectury {
    common("fabric", "neoforge")
}

base {
    archivesName = "${project.mod_id}-common"
}

repositories {
    maven {
        name = "Fabric"
        url = "https://maven.fabricmc.net/"
    }

    maven {
        name = "CurseMaven"
        url = "https://www.cursemaven.com"
    }

    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
    }

    maven {
        name = "DAQEM"
        url = "https://maven.daqem.com/releases"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"

    mappings loom.officialMojangMappings()

    modImplementation "com.daqem.knot:knot-common:${knot_version}"
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}