plugins {
    id "fabric-loom" version "1.17-SNAPSHOT"
}

base {
    archivesName = "${project.mod_id}-common"
}

repositories {
    maven {
        name = "Fabric"
        url = "https://maven.fabricmc.net/"
    }

    maven {
        name = "CurseMaven"
        url = "https://www.cursemaven.com"
    }

    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
    }

    maven {
        name = "Architectury"
        url = "https://maven.architectury.dev/"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"

    mappings loom.officialMojangMappings()

    modImplementation(
            "net.fabricmc:fabric-language-kotlin:${fabric_kotlin_version}"
    )
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}