modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="Aris"
authors="GrindlesStudio"
description='''
Aris — реалистичная генерация мира Minecraft.
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[21.11,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[1.21.11]"
ordering="NONE"
side="BOTH"

[[mixins]]
config="aris.mixins.json"