plugins {
    id "net.neoforged.moddev" version "2.0.147"
}

base {
    archivesName = "${project.mod_id}-neoforge"
}

neoForge {
    version = neoforge_version

    runs {
        client {
            client()

            gameDirectory = project.file("runs/client")

            systemProperty(
                    "neoforge.enabledGameTestNamespaces",
                    mod_id
            )
        }

        server {
            server()

            gameDirectory = project.file("runs/server")

            systemProperty(
                    "neoforge.enabledGameTestNamespaces",
                    mod_id
            )
        }
    }

    mods {
        "${project.mod_id}" {
            sourceSet sourceSets.main
            sourceSet project(":common").sourceSets.main
        }
    }
}

dependencies {
    implementation project(":common")

    implementation "org.jetbrains.kotlin:kotlin-reflect:${kotlin_version}"
    implementation "org.jetbrains.kotlin:kotlin-stdlib:${kotlin_version}"
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
}

kotlin {
    jvmToolchain(25)
}

jar {
    dependsOn(":common:classes")

    from(project(":common").sourceSets.main.output)
}

tasks.processResources {
    inputs.properties(
            "version": project.version,
            "mod_id": project.mod_id,
            "mod_version": project.mod_version,
            "minecraft_version": project.minecraft_version
    )

    filesMatching("META-INF/neoforge.mods.toml") {
        expand(
                "version": project.version,
                "mod_id": project.mod_id,
                "mod_version": project.mod_version,
                "minecraft_version": project.minecraft_version
        )
    }
}