plugins {
    id "net.neoforged.moddev" version "2.0.107"
}

base {
    archivesName = "${project.mod_id}-neoforge"
}

dependencies {
    // Common
    implementation project(":common")

    // TerraBlender NeoForge
    implementation(
            "maven.modrinth:kkmrDlKT:${terrablender_neoforge_id}"
    )

    implementation(
            "com.daqem.knot:knot-neoforge:${knot_version}"
    )
    //Kotlin for Forge
    implementation (
            "maven.modrinth:ordsPcFz:WSKgpZoB"
    )
}

neoForge {
    version = neoforge_version

    runs {
        client {
            client()
            gameDirectory = project.file("runs/client")

            systemProperty(
                    "neoforge.enabledGameTestNamespaces",
                    mod_id
            )
        }

        server {
            server()
            gameDirectory = project.file("runs/server")

            systemProperty(
                    "neoforge.enabledGameTestNamespaces",
                    mod_id
            )
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
            sourceSet project(":common").sourceSets.main
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}